package Utils;

public enum MessageType {
    LOGIN_REQUEST,
    LOGIN_OK,
    LOGIN_FAIL,
    LOOKUP_STD,
    SERVER_RESPONSE,
    LOOKUP_FILES_OTHER,
    LOOKUP_FILES_SELF,
    FILE_REQUEST,
    FILE_LIST,
    REQUEST,
    FILE_ACCEPT,
    FILE_REJECT,
    FILE_UL_COMPLETE,
    BUFFER_FULL,
    UNREAD_MESSAGE,
    ANNOUNCE,
    LOGOUT,
    CHUNK_RECEIVED,
    FILE_TIMEOUT,
    FILE_INIT,
    FILE_DL,
    ERROR,
    BROADCAST
}
